### ISSUE TITLE
CSS suggestion

### ISSUE THREAD

**Issue by E-fais** [aparna2071/Responsive-Aparna-Portfolio#1]
Hey , if you can make images little bit smaller,add boxshadow and border radius, it will look much better.

**Comment by aparna2071** [comment]
Thank you so much for opening this issue & showing interest in my project.
Do you want to contribute to it ?

**Comment by E-fais** [comment]
> Thank you so much for opening this issue & showing interest in my project.
> Do you want to contribute to it ?

Yes , I would like to work on this issue 👍

**Comment by aparna2071** [comment]
great, go ahead 👍

**Comment by E-fais** [comment]
since you are using a template , i felt little bit hard to understand the code, some how i have managed to make small changes. 
I hope you like it.
